version: '3.1'

services:

  db:
    image: mysql:9.6

    restart: always
    env_file:
      - ./.env
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$MYSQL_ROOT_PASSWORD -e 'USE $MYSQL_DATABASE; SHOW TABLES LIKE \"users\";' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3

  adminer:
    depends_on:
      db:
        condition: service_healthy
    image: adminer
    restart: no
    ports:
      - 8080:8080

  api:
    build:
      context: ./server
    image: theolafond/api_fastapi:0.0.3
    restart: no
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: db
    env_file:
      - ./server/.env
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/users')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./app
      dockerfile: react.Dockerfile
    container_name: react_front
    restart: no
    ports:
      - 5173:5173
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    command: pnpm dev --host
